# Generated by Django 5.2.2 on 2025-06-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
