# Generated by Django 5.2.2 on 2025-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0004_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetail',
            name='title',
            field=models.TextField(),
        ),
    ]
