# Generated by Django 5.2.2 on 2025-06-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0005_alter_imagedetail_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='detail',
            field=models.TextField(default='No details available'),
        ),
        migrations.AlterField(
            model_name='imagedetail',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
